import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category', 
      label: 'Introduction to Physical AI',
      items: [{type: 'autogenerated', dirName: '01-Introduction-to-Physical-AI'}],
    },
    {
      type: 'category',
      label: 'ROS2 Basics',
      items: [{type: 'autogenerated', dirName: '02-ROS2-Basics'}],
    },
    {
      type: 'category',
      label: 'Sensors and Actuators',
      items: [{type: 'autogenerated', dirName: '03-Sensors-and-Actuators'}],
    },
    {
      type: 'category',
      label: 'Robot Modeling and Simulation',
      items: [{type: 'autogenerated', dirName: '04-Robot-Modeling-and-Simulation'}],
    },
    {
      type: 'category',
      label: 'NVIDIA Isaac Platform',
      items: [{type: 'autogenerated', dirName: '05-NVIDIA-Isaac-Platform'}],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics',
      items: [{type: 'autogenerated', dirName: '06-Humanoid-Robotics'}],
    },
    {
      type: 'category',
      label: 'AI for Robotics',
      items: [{type: 'autogenerated', dirName: '07-AI-for-Robotics'}],
    },
    {
      type: 'category',
      label: 'Virtual Learning Assistant',
      items: [{type: 'autogenerated', dirName: '08-Virtual-Learning-Assistant'}],
    },
  ],
};

export default sidebars;
